const all = [
  {
    "id": "1",
    "description": "Dall'interno della grotta si guarda verso l'uscita. L'azzurro dell'acqua si riflette sulla volta e sulle pareti dell'antro. Notte con luna.",
    "description_en": "A cave looking towards an exit. The water reflects on the walls of the cave. Full moon night.",
    "category": "Night",
    "SpriteReference": "1_sprite",
    "CubemapReference": "1_HDR",
    "Narrator": "É notte, c'é la luna.",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "10",
    "NarratorTranslation": "Ok so - it's night, the moon is out. At the center of the scene is an object...",
    "NarratorTranslationEs": "Bien, es de noche, hay luna. En el centro de la escena hay un objeto...",
    "phoneCategoryIt": "in una grotta",
    "phoneCategoryEn": "in a cave",
    "phoneCategoryEs": "en una cueva"
  },
  {
    "id": "2",
    "description": "Portico con volte a crociera e scale. Dagli occhi di portico si intravede un cortile. Notte.",
    "description_en": "A portico with vaults and stairs. A courtyard is visible. It's night.",
    "category": "Night",
    "SpriteReference": "2_sprite",
    "CubemapReference": "2_HDR",
    "Narrator": "Ok! Si comincia. Studiamo la scena: portico, volte, cortile… e notte.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "12.4",
    "NarratorTranslation": "Let's begin, let's study the scene: portico, vaults, courtyard, night.. at the center of the scene an object",
    "NarratorTranslationEs": "Comencemos, estudiemos la escena: pórtico, bóvedas, patio, noche... En el centro de la escena hay un objeto.",
    "phoneCategoryIt": "in un portico",
    "phoneCategoryEn": "under a portico",
    "phoneCategoryEs": "en un pórtico"
  },
  {
    "id": "3",
    "description": "Notte, luna piena. Un vialetto di cimitero circondato da cipressi si snoda fra tombe di varie tipologie. In fondo si intravede l'uscita del cimitero.",
    "description_en": "Night, full moon. A cemetery path is surrounded by cypresses and graves of various kinds. The exit of the cemetery is visible.",
    "category": "Night",
    "SpriteReference": "3_sprite",
    "CubemapReference": "3_HDR",
    "Narrator": "É notte, c'é la luna.",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "7.8",
    "NarratorTranslation": "Ok so - it's night, the moon is out, in the middle of the scene is an object",
    "NarratorTranslationEs": "Bien, es de noche, hay luna, en el centro de la escena hay un objeto.",
    "phoneCategoryIt": "al cimitero",
    "phoneCategoryEn": "in a cemetery",
    "phoneCategoryEs": "en un cementerio"
  },
  {
    "id": "4",
    "description": "Un ampio androne con passaggi dai soffitti a volta è illuminato da una lama di luce che sembra venire dall'interno del castello. Da uno dei passaggi si vede un cortile interno. Notte.",
    "description_en": "A big entrance hall with high ceilings is lit by a strip of light that seems to come from inside the castle. An inner courtyard is visible from one of the passages. Night.",
    "category": "Night",
    "SpriteReference": "4_sprite",
    "CubemapReference": "4_HDR",
    "Narrator": "É notte, c'é la luna.",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "10.8",
    "NarratorTranslation": "Ok so - it's night, the moon is out, in the middle of the scene is an object...",
    "NarratorTranslationEs": "Bien, es de noche, hay luna, en el centro de la escena hay un objeto...",
    "phoneCategoryIt": "in un androne",
    "phoneCategoryEn": "in a hallway",
    "phoneCategoryEs": "en un pasillo"
  },
  {
    "id": "5",
    "description": "Veduta di piazza con chiesa e campanile nel fondo. A destra un palazzo con portico. Nella piazza sono presenti numerosi lampioni che gettano la loro lunga ombra nel chiaro di luna della notte.",
    "description_en": "View of a square with a church and bell tower in the background. On the right, a building with a portico. In the square, there are many street lamps that cast long shadows in the moonlight of the night.",
    "category": "Night",
    "SpriteReference": "5_sprite",
    "CubemapReference": "5_HDR",
    "Narrator": "É notte, c'é la luna.",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "7.4",
    "NarratorTranslation": "Ok so - it's night, the moon is out, in the middle of the scene is an object...",
    "NarratorTranslationEs": "Bien, es de noche, hay luna, en el centro de la escena hay un objeto...",
    "phoneCategoryIt": "in piazza",
    "phoneCategoryEn": "in a square",
    "phoneCategoryEs": "en una plaza"
  },
  {
    "id": "6",
    "description": "Visione notturna di un tranquillo chiostro, circondato da un portico.",
    "description_en": "Night view of a quiet chiostro, surrounded by a portico.",
    "category": "Night",
    "SpriteReference": "6_sprite",
    "CubemapReference": "6_HDR",
    "Narrator": "Allora, questa scena si svolge di notte. Siamo in un portico tranquillo.",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "7.6",
    "NarratorTranslation": "So, this scene takes place at night, we are in a quiet porch. In the middle of the scene is an object",
    "NarratorTranslationEs": "Esta escena transcurre de noche, estamos en un tranquilo porche. En el centro de la escena hay un objeto.",
    "phoneCategoryIt": "in un chiostro",
    "phoneCategoryEn": "in a cloister",
    "phoneCategoryEs": "en un claustro"
  },
  {
    "id": "7",
    "description": "Venezia, con l'isola di San Giorgio e la laguna illuminate dalla luna di notte.",
    "description_en": "Venice, with the island of San Giorgio and the lagoon illuminated by the moon at night.",
    "category": "Night",
    "SpriteReference": "7_sprite",
    "CubemapReference": "7_HDR",
    "Narrator": "Allora. Siamo a Venezia.",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "9.3",
    "NarratorTranslation": "So, we are in Venice. In the middle of the scene is an object",
    "NarratorTranslationEs": "Estamos en Venecia. En el centro de la escena hay un objeto.",
    "phoneCategoryIt": "a Venezia",
    "phoneCategoryEn": "in Venice",
    "phoneCategoryEs": "en Venecia"
  },
  {
    "id": "8",
    "description": "La luna raffigurata come un volto di profilo sorge su un globo azzurro.",
    "description_en": "The moon depicted as a face in profile rises on a blue globe.",
    "category": "Night",
    "SpriteReference": "8_sprite",
    "CubemapReference": "8_HDR",
    "Narrator": "Qua dobbiamo usare l'immaginazione maschere. Improvvisiamo una scena astratta, con la luna che guarda un globo.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "13.8",
    "NarratorTranslation": "Here we have to use imagination masks. We see the moon looking at a globe. In the middle of the scene is an object",
    "NarratorTranslationEs": "Aquí tenemos que usar la imaginación, máscaras. Vemos la luna mirando un globo terráqueo. En el centro de la escena hay un objeto.",
    "phoneCategoryIt": "in cielo",
    "phoneCategoryEn": "in the sky",
    "phoneCategoryEs": "en el cielo"
  },
  {
    "id": "9",
    "description": "Paesaggio con mare agitato da onde spumose. Nelle parte destra lo specchio di mare è delimitato da alture. Il cielo ha qualche leggera nube.",
    "description_en": "Landscape with a sea agitated by waves. On the right side the sea are hills. The sky has some light clouds.",
    "category": "OutdoorNature",
    "SpriteReference": "9_sprite",
    "CubemapReference": "9_HDR",
    "Narrator": "Bene, siamo al mare, una bella scena.",
    "NarratorLengthIt": "6.3",
    "NarratorLength": "9.6",
    "NarratorTranslation": "Well, we are at the seaside, a beautiful scene. Here on stage is an object...",
    "NarratorTranslationEs": "Bueno, estamos en la playa, una escena preciosa. Aquí en el escenario hay un objeto...",
    "phoneCategoryIt": "al mare",
    "phoneCategoryEn": "at sea",
    "phoneCategoryEs": "en el mar"
  },
  {
    "id": "10",
    "description": "Alcuni alberi in un paesaggio brullo. Sulla destra si vede un muretto. Nello sfondo, in lontananza, si innalzano delle colline.",
    "description_en": "Some trees in a barren landscape. On the right, a low wall. In the background, in the distance, some hills rise.",
    "category": "OutdoorNature",
    "SpriteReference": "10_sprite",
    "CubemapReference": "10_HDR",
    "Narrator": "Allora questa scena la facciamo all'aria aperta. Ok!?",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "10",
    "NarratorTranslation": "So, this scene is outdoors, ok? And in the middle of the scene, an object...",
    "NarratorTranslationEs": "Esta escena es al aire libre, ¿vale? Y en medio de la escena, un objeto...",
    "phoneCategoryIt": "in campagna",
    "phoneCategoryEn": "in the countryside",
    "phoneCategoryEs": "en el campo"
  },
  {
    "id": "11",
    "description": "Una campagna innevata, con stradine. A destra un borgo con campanile. A sinistra una casa colonica. In lontananza si vede una chiesa sullo sfondo di monti innevati.",
    "description_en": "A snow-covered countryside with small streets. On the right a village with a bell tower. On the left a farmhouse. In the distance, a church against the backdrop of snowy mountains",
    "category": "OutdoorNature",
    "SpriteReference": "11_sprite",
    "CubemapReference": "11_HDR",
    "Narrator": "Attenzione maschere. Siete in campagna apera ed é nevicato.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "9.6",
    "NarratorTranslation": "Attention masks. You are in the open countryside and it has snowed. And here in the middle is an object...",
    "NarratorTranslationEs": "Máscaras, atención. Estáis en pleno campo y ha nevado. Y aquí, en medio, hay un objeto...",
    "phoneCategoryIt": "in campagna",
    "phoneCategoryEn": "in the countryside",
    "phoneCategoryEs": "en el campo"
  },
  {
    "id": "12",
    "description": "Tronchi d'albero a perdita d'occhio occupano quasi tutta la scena. Nella parte alta si vede l'inizio delle chiome.",
    "description_en": "Tree trunks as far as the eye can see occupy almost the entire scene. In the upper part is the beginning of the foliage.",
    "category": "OutdoorNature",
    "SpriteReference": "12_sprite",
    "CubemapReference": "12_HDR",
    "Narrator": "Eccoci, in questa scena siamo in una foresta piuttosto fitta.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "9.4",
    "NarratorTranslation": "Here we are, in this scene we are in a rather thick forest. Look in the middle, there's an object",
    "NarratorTranslationEs": "Aquí estamos, en esta escena, en un bosque bastante espeso. Mira en el medio, hay un objeto.",
    "phoneCategoryIt": "in un bosco",
    "phoneCategoryEn": "in a forest",
    "phoneCategoryEs": "en un bosque"
  },
  {
    "id": "14",
    "description": "Ai piedi di alcuni alberi, fra le rocce si vede l'ingresso di una grotta.",
    "description_en": "At the foot of some trees, among the rocks, the entrance to a cave.",
    "category": "OutdoorNature",
    "SpriteReference": "14_sprite",
    "CubemapReference": "14_HDR",
    "Narrator": "Maschere - occhio alla scena. Siamo all'aperto, in mezzo alla natura.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "10.4",
    "NarratorTranslation": "Ok let's study the scene, we are outdoors, in the middle of nature, and in the center is an object",
    "NarratorTranslationEs": "Bien, estudiemos la escena: estamos al aire libre, en plena naturaleza, y en el centro hay un objeto.",
    "phoneCategoryIt": "in campagna",
    "phoneCategoryEn": "in the countryside",
    "phoneCategoryEs": "en el campo"
  },
  {
    "id": "15",
    "description": "Nelle parte sinistra lo specchio di mare è delimitato da alture. Il cielo è sfumato di azzurro e verde chiaro.",
    "description_en": "On the left side the sea is bordered by hills. The sky is blue and light green.",
    "category": "OutdoorNature",
    "SpriteReference": "15_sprite",
    "CubemapReference": "15_HDR",
    "Narrator": "Bene, siamo al mare, una bella scena.",
    "NarratorLengthIt": "6.3",
    "NarratorLength": "8.4",
    "NarratorTranslation": "Nice, we are on the seaside, a nice scene. Here on stage is an object...",
    "NarratorTranslationEs": "Genial, estamos a la orilla del mar, una escena bonita. Aquí, en el escenario, hay un objeto...",
    "phoneCategoryIt": "al mare",
    "phoneCategoryEn": "at sea",
    "phoneCategoryEs": "en el mar"
  },
  {
    "id": "16",
    "description": "Interno di prigione con colonne a sostegno delle volte. Da una finestra entra un raggio di luce che illumina parte del muro.",
    "description_en": "Interior of a prison with columns supporting the vaults. A ray of light enters from a window and illuminates part of the wall.",
    "category": "Sinister",
    "SpriteReference": "16_sprite",
    "CubemapReference": "16_HDR",
    "Narrator": "Allora, siamo in una prigione.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "6.4",
    "NarratorTranslation": "We are in a prison. Here in the middle of the scene you see an object. Ok.",
    "NarratorTranslationEs": "Estamos en una prisión. Aquí, en medio de la escena, veis un objeto. Bien.",
    "phoneCategoryIt": "in una prigione",
    "phoneCategoryEn": "in a prison",
    "phoneCategoryEs": "en una prisión"
  },
  {
    "id": "19",
    "description": "Una bella stanza con parete verde chiaro. Mattone con marmorizzazione. Una porta tra uno specchio rettangolare ed uno ovale.",
    "description_en": "A beautiful room with a light green wall. Brick with marbling. There's a door between a rectangular and an oval mirror.",
    "category": "InteriorRegal",
    "SpriteReference": "19_sprite",
    "CubemapReference": "19_HDR",
    "Narrator": "Maschere, in questa scena siete in una bella stanza, una stanza da signori.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "11",
    "NarratorTranslation": "Ok, you are in a nice room, a gentleman's room. In the center you see an object.",
    "NarratorTranslationEs": "Bien, estás en una habitación bonita, la habitación de un caballero. En el centro ves un objeto.",
    "phoneCategoryIt": "in una camera",
    "phoneCategoryEn": "in a room",
    "phoneCategoryEs": "en una habitación"
  },
  {
    "id": "21",
    "description": "Cornicioni in varie tonalità di verde. Soffitto blu-indaco e pareti rosse.",
    "description_en": "A room with cornices in shades of green, blue ceiling and red walls.",
    "category": "InteriorRegal",
    "SpriteReference": "21_sprite",
    "CubemapReference": "21_HDR",
    "Narrator": "Eccoci. Guardate che bella scena, che colori blu e rossi.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "13.2",
    "NarratorTranslation": "Here we are. Look at this beautiful scene, what blue and red colors. So, in the middle of the scene is an object...",
    "NarratorTranslationEs": "Aquí estamos. Mira esta hermosa escena, qué colores azules y rojos. Entonces, en medio de la escena hay un objeto...",
    "phoneCategoryIt": "in un atrio",
    "phoneCategoryEn": "in a hall",
    "phoneCategoryEs": "en una sala"
  },
  {
    "id": "22",
    "description": "Un ampio androne con soffitto a volta conduce ad un cortile e ad un altro passaggio soffuso di luce rosata.",
    "description_en": "A large hall with a vaulted ceiling leads to a courtyard, and another passage washed in pink light.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "22_sprite",
    "CubemapReference": "22_HDR",
    "Narrator": "Eccoci. Che bell'edificio. Osservatelo.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "8",
    "NarratorTranslation": "Here we are. What a beautiful building. Look at it. And look at the center is an object, ok?",
    "NarratorTranslationEs": "Aquí estamos. Qué hermoso edificio. Míralo. Y mira, en el centro hay un objeto, ¿de acuerdo?",
    "phoneCategoryIt": "in un androne",
    "phoneCategoryEn": "in a hall",
    "phoneCategoryEs": "en una sala"
  },
  {
    "id": "23",
    "description": "Una grande quantità di scheletri uno sopra all'altro creano una macabra porta.",
    "description_en": "A macabre door made out of a large quantity of skeletons.",
    "category": "Sinister",
    "SpriteReference": "23_sprite",
    "CubemapReference": "23_HDR",
    "Narrator": "Eccoci. Guardiamoci intorno - una scena piuttosto sinistra.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "6.4",
    "NarratorTranslation": "Here we are. Let's look around - a rather sinister scene. In the middle you see an object",
    "NarratorTranslationEs": "Aquí estamos. Miremos a nuestro alrededor: una escena bastante siniestra. En el centro se ve un objeto.",
    "phoneCategoryIt": "nelle cripte",
    "phoneCategoryEn": "in a crypt",
    "phoneCategoryEs": "en una cripta"
  },
  {
    "id": "26",
    "description": "Ingresso al circo con struttura che sostiene la tabella con la scritta \"circo\". Appesi alla struttura anche uno stendardo col volto di un clown e un cartello con la scritta \"questa sera ore 21\".",
    "description_en": "A circus entrance. A sign that reads \"circus\" is supported by a structute. A banner with a clown's face also hangs from it, and a sign with the words \"this evening at 9:00 p.m.\"",
    "category": "Festive",
    "SpriteReference": "26_sprite",
    "CubemapReference": "26_HDR",
    "Narrator": "Allora, siamo al circo!",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "9.4",
    "NarratorTranslation": "So we are at the circus, and in the middle of the scene there is an object, ok?",
    "NarratorTranslationEs": "Estamos en el circo, y en el centro de la escena hay un objeto, ¿vale?",
    "phoneCategoryIt": "al circo",
    "phoneCategoryEn": "at the circus",
    "phoneCategoryEs": "en el circo"
  },
  {
    "id": "29",
    "description": "Sarcofagi e croci disseminati in un prato circondato da cipressi.",
    "description_en": "Winter, dawn. Tombs and crosses are scattered in a meadow, surrounded by cypress trees.",
    "category": "Night",
    "SpriteReference": "29_sprite",
    "CubemapReference": "29_HDR",
    "Narrator": "Eccoci. Guardiamoci intorno - una scena piuttosto sinistra.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Here we are. Let's look around - a rather sinister scene. In the middle you see an object",
    "NarratorTranslationEs": "Aquí estamos. Miremos a nuestro alrededor: una escena bastante siniestra. En el centro se ve un objeto.",
    "phoneCategoryIt": "al cimitero",
    "phoneCategoryEn": "at the cemetery",
    "phoneCategoryEs": "en el cementerio"
  },
  {
    "id": "30",
    "description": "Sala con fuga di archi moreschi, sostenuti da colonne a tortiglione. Pareti dipinte con motivi floreali stilizzati e geometrici.",
    "description_en": "A room with a series of Moorish arches, supported by twisted columns. The walls are painted with floral and geometric patterns.",
    "category": "InteriorRegal",
    "SpriteReference": "30_sprite",
    "CubemapReference": "30_HDR",
    "Narrator": "bene, la scena è ambientata in un posto molto speciale, con decorazioni orientalizzanti... insomma interpretate voi.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "10.9",
    "NarratorTranslation": "Well, the scene is set in a very special place, with oriental decorations... In the middle, an object...",
    "NarratorTranslationEs": "Bueno, la escena está ambientada en un lugar muy especial, con decoraciones orientales... puedes interpretarlo. En el centro, un objeto...",
    "phoneCategoryIt": "in un atrio",
    "phoneCategoryEn": "in a hall",
    "phoneCategoryEs": "en una sala"
  },
  {
    "id": "34",
    "description": "Sala con tre finestroni ad arco protetti da tendaggi. Pavimento a rombi rossi e blu.",
    "description_en": "A room with three arched windows and curtains. The floor has red and blue diamonds.",
    "category": "InteriorRegal",
    "SpriteReference": "34_sprite",
    "CubemapReference": "34_HDR",
    "Narrator": "Maschere, in questa scena siete in una bella stanza, una stanza da signori.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "9.8",
    "NarratorTranslation": "Ok, you are in a nice room, a gentleman's room. In the center you see an object.",
    "NarratorTranslationEs": "Bueno, estás en una bonita habitación, la habitación de un caballero. En el centro se ve un objeto.",
    "phoneCategoryIt": "in una sala",
    "phoneCategoryEn": "in a room",
    "phoneCategoryEs": "en una habitación"
  },
  {
    "id": "39",
    "description": "Nella parete di fondo della sala, dipinta in azzurro, si aprono due porte schermate da tendaggi blu. Al centro della stessa parete, gli stalli dei consiglieri sono posti su una pedana.",
    "description_en": "A regal room with two light blue doors shielded by blue curtains.",
    "category": "InteriorRegal",
    "SpriteReference": "39_sprite",
    "CubemapReference": "39_HDR",
    "Narrator": "Maschere, in questa scena siete in una bella stanza, una stanza da signori.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "7.9",
    "NarratorTranslation": "Ok, you are in a nice room, a gentleman's room. In the center you see an object.",
    "NarratorTranslationEs": "Bueno, estás en una bonita habitación, la habitación de un caballero. En el centro se ve un objeto.",
    "phoneCategoryIt": "in una villa",
    "phoneCategoryEn": "in a villa",
    "phoneCategoryEs": "en una villa"
  },
  {
    "id": "40",
    "description": "Stanza vista in prospettiva centrale. Pareti di colore rosa carico. Pavimento a scacchi. Al centro della parete di fondo campeggia un orologio a pendolo.",
    "description_en": "A room seen from a central perspective, walls of deep pink, checkered floor, a pendulum clock on the back wall.",
    "category": "InteriorRegal",
    "SpriteReference": "40_sprite",
    "CubemapReference": "40_HDR",
    "Narrator": "Bene, siamo in una bellissima stanza regale.",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "8.4",
    "NarratorTranslation": "Well, we are in a beautiful royal room. In the middle of the scene, an object",
    "NarratorTranslationEs": "Bueno, estamos en una hermosa habitación real. En el centro de la escena, un objeto.",
    "phoneCategoryIt": "in una villa",
    "phoneCategoryEn": "in a villa",
    "phoneCategoryEs": "en una villa"
  },
  {
    "id": "41",
    "description": "Interno di grotta con pertugio che guarda verso il mare aperto, dove si nota uno scoglio isolato. Il cielo è nuvoloso e il mare spumoso. All'interno della grotta si vedono riflessi di luce dorata.",
    "description_en": "Interior of a cave with a hole looking out to the sea. The sky is cloudy, the sea is foamy. Inside the cave there's reflections of golden light.",
    "category": "Sinister",
    "SpriteReference": "41_sprite",
    "CubemapReference": "41_HDR",
    "Narrator": "Ok. Siamo in una grotta.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "5.2",
    "NarratorTranslation": "We are in a cave. At the center you see an object.",
    "NarratorTranslationEs": "Estamos en una cueva. En el centro se ve un objeto.",
    "phoneCategoryIt": "in una grotta",
    "phoneCategoryEn": "in a cave",
    "phoneCategoryEs": "en una cueva"
  },
  {
    "id": "44",
    "description": "Ingresso al circo con varco protetto da un tendaggio rosso.",
    "description_en": "Three entrances to the circus, with red curtains around them.",
    "category": "Festive",
    "SpriteReference": "44_sprite",
    "CubemapReference": "44_HDR",
    "Narrator": "Allora, siamo al circo!",
    "NarratorLengthIt": "6.7",
    "NarratorLength": "6.6",
    "NarratorTranslation": "So we are at the circus, and in the middle of the scene there is an object, ok?",
    "NarratorTranslationEs": "Estamos en el circo, y en el centro de la escena hay un objeto, ¿vale?",
    "phoneCategoryIt": "al circo",
    "phoneCategoryEn": "at the circus",
    "phoneCategoryEs": "en el circo"
  },
  {
    "id": "45",
    "description": "Ampio fossato con ponte che unisce un torrione al castello.",
    "description_en": "A wide canal with a bridge on top connecting a tower to a castle.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "45_sprite",
    "CubemapReference": "45_HDR",
    "Narrator": "Eccoci. Che bell'edificio. Osservatelo.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "8.1",
    "NarratorTranslation": "Here we are. What a beautiful building. Look at it. And look at the center is an object, ok?",
    "NarratorTranslationEs": "Aquí estamos. Qué bonito edificio. Míralo. Y mira, en el centro hay un objeto, ¿vale?",
    "phoneCategoryIt": "in un castello",
    "phoneCategoryEn": "in a castle",
    "phoneCategoryEs": "en un castillo"
  },
  {
    "id": "46",
    "description": "Stanza vista in prospettiva centrale dominata da un grande camino. Nel soffitto si vedono travi grezze, sotto l'intonaco si intravedono i mattoni.",
    "description_en": "A humble room, dominated by a large fireplace, with rough beams o nthe ceiling and some bricks showing on the wall",
    "category": "InteriorHumble",
    "SpriteReference": "46_sprite",
    "CubemapReference": "46_HDR",
    "Narrator": "Bene, salve maschere. La scena si svolge all'interno, in una stanza con un gran camino.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "8.2",
    "NarratorTranslation": "Hello masks! The scene takes place indoors, in a room with a large fireplace. In the middle, an object",
    "NarratorTranslationEs": "¡Hola, máscaras! La escena se desarrolla en un interior, en una habitación con una gran chimenea. En el centro, un objeto.",
    "phoneCategoryIt": "in una stanza",
    "phoneCategoryEn": "in a room",
    "phoneCategoryEs": "en una habitación"
  },
  {
    "id": "47",
    "description": "Un'osteria. In una sala con colonne che reggono volte a crociera, si vedono un tavolo con sedie, una botte e una credenza. Attraverso un passaggio ad arco vi è l'accesso ad una scala per il piano superiore.",
    "description_en": "A large inn, with columns and arches, tables and chairs, and a big wine barrel at the other end of the room. A staircase to the upper floor is visible through the arched passage.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "47_sprite",
    "CubemapReference": "47_HDR",
    "Narrator": "Bene. Siamo in osteria. Una grande osteria, viva, piena!",
    "NarratorLengthIt": "6",
    "NarratorLength": "5.4",
    "NarratorTranslation": "Ok, we are in a tavern. Here you see an object, ok?",
    "NarratorTranslationEs": "Bueno, estamos en una taberna. Aquí ven un objeto, ¿de acuerdo?",
    "phoneCategoryIt": "in osteria",
    "phoneCategoryEn": "in an inn",
    "phoneCategoryEs": "en una posada"
  },
  {
    "id": "48",
    "description": "Sala dal soffitto con stucchi decorativi, colonne con specchiature verdi, pavimento a scacchi. Nel fondo si apre una porta con tendaggio. Da una finestra a sinistra la luce del sole si proietta sul pavimento.",
    "description_en": "A regal room with a stucco ceiling, columns with green mirrors, and checkered floor. In the back there is a door with a curtain. The sunlight is projected onto the floor from a window on the left.",
    "category": "InteriorRegal",
    "SpriteReference": "48_sprite",
    "CubemapReference": "48_HDR",
    "Narrator": "Maschere, in questa scena siete in una bella stanza, una stanza da signori.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "7",
    "NarratorTranslation": "Ok, you are in a nice room, a gentleman's room. In the center you see an object.",
    "NarratorTranslationEs": "Bueno, están en una bonita habitación, la de un caballero. En el centro ven un objeto.",
    "phoneCategoryIt": "in una villa",
    "phoneCategoryEn": "in a villa",
    "phoneCategoryEs": "en una villa"
  },
  {
    "id": "50",
    "description": "Al centro della scena, al vertice di una scalinata si trova il trono. A destra e a sinistra una fitta teoria di colonne e di basamenti con animali mitologici. Scena dai colori brillanti.",
    "description_en": "A brigh, colorful room, with a small staircase leading to a throne. On the right and left a dense series of columns and bases with mythological animals",
    "category": "InteriorRegal",
    "SpriteReference": "50_sprite",
    "CubemapReference": "50_HDR",
    "Narrator": "bene, la scena è ambientata in un posto molto speciale, con decorazioni orientalizzanti... insomma interpretate voi.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "9.9",
    "NarratorTranslation": "Well, the scene is set in a very special place, with oriental decorations... you can interpret that. In the middle, an object...",
    "NarratorTranslationEs": "Bueno, la escena se desarrolla en un lugar muy especial, con decoraciones orientales... se puede interpretar. En el centro, un objeto...",
    "phoneCategoryIt": "in un atrio",
    "phoneCategoryEn": "in an hall",
    "phoneCategoryEs": "en un pasillo"
  },
  {
    "id": "54",
    "description": "Stanza vista in prospettiva centrale, piuttosto spoglia, con camino, un tavolo e una sedia.",
    "description_en": "A humble room seen in central perspective, rather bare, with a fireplace, a table and a chair.",
    "category": "InteriorHumble",
    "SpriteReference": "54_sprite",
    "CubemapReference": "54_HDR",
    "Narrator": "Allora, siamo in una stanza abbastanza semplice.. con un caminetto.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "8.4",
    "NarratorTranslation": "So, we're in a pretty simple room, with a fireplace, and in the middle of the room is an object",
    "NarratorTranslationEs": "Así que estamos en una habitación bastante sencilla, con chimenea, y en el centro hay un objeto.",
    "phoneCategoryIt": "in una stanza",
    "phoneCategoryEn": "in a room",
    "phoneCategoryEs": "en una habitación"
  },
  {
    "id": "55",
    "description": "Veduta di prospetto di un edificio, con pronao a quattro colonne e timpano, che occupa il lato di una piazza.",
    "description_en": "View of a square with buildings. At the center, the front of a tall building with four tall columns and large steps.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "55_sprite",
    "CubemapReference": "55_HDR",
    "Narrator": "Eccoci, partiamo dalla scena. Siamo in piazza.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "10",
    "NarratorTranslation": "Ok, let's start from the scene, we are in a square, and in the middle of the scene you can see a prop.",
    "NarratorTranslationEs": "Bueno, empecemos por la escena: estamos en una plaza, y en el centro se ve un objeto de utilería.",
    "phoneCategoryIt": "in piazza",
    "phoneCategoryEn": "in a square",
    "phoneCategoryEs": "en una plaza"
  },
  {
    "id": "57",
    "description": "Entrata delle prigioni, si nota sulla destra la discesa dal castello. Su una piccola scalinata una finestra con grata e una porta. Al centro una colonna sorregge le volte.",
    "description_en": "Entrance to a prison, with a central column supporting the vaults in the center. On the the right, a locked door leading to the castle. On a small staircase a small wooden door.",
    "category": "Sinister",
    "SpriteReference": "57_sprite",
    "CubemapReference": "57_HDR",
    "Narrator": "Allora, siamo in una prigione.",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "9.1",
    "NarratorTranslation": "We are in a prison. Here in the middle of the scene you see an object. Ok.",
    "NarratorTranslationEs": "Estamos en una prisión. Aquí, en el centro de la escena, ven un objeto. Bien.",
    "phoneCategoryIt": "in una prigione",
    "phoneCategoryEn": "in a prison",
    "phoneCategoryEs": "en una prisión"
  },
  {
    "id": "59",
    "description": "L'arena del circo con tre ordini di stalli per gli spettatori.",
    "description_en": "A circus arena, with three tiers of specators stalls.",
    "category": "Festive",
    "SpriteReference": "59_sprite",
    "CubemapReference": "59_HDR",
    "Narrator": "Allora. Ci troviamo in una grande arena. Molta gente! E qua in mezzo, un oggetto.  ok?",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "10.1",
    "NarratorTranslation": "So. We are in a big arena. Lots of people! And here in the middle, an object. OK?",
    "NarratorTranslationEs": "Entonces. Estamos en un gran estadio. ¡Mucha gente! Y aquí, en el centro, un objeto. ¿De acuerdo?",
    "phoneCategoryIt": "al circo",
    "phoneCategoryEn": "at the circus",
    "phoneCategoryEs": "en el circo"
  },
  {
    "id": "64",
    "description": "Stanza umile con scala all'ingresso, arredata solo con un tavolo e una sedia.",
    "description_en": "A humble room with a staircase at the entrance, furnished only with a table and a chair.",
    "category": "InteriorHumble",
    "SpriteReference": "64_sprite",
    "CubemapReference": "64_HDR",
    "Narrator": "Eccoci. Che tristezza sta stanza eh..?",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "9",
    "NarratorTranslation": "Here we are. How sad is this room... And in the middle of the scene is a prop.",
    "NarratorTranslationEs": "Aquí estamos. Qué triste es esta habitación... Y en el centro de la escena hay un utensilio.",
    "phoneCategoryIt": "in una stanza",
    "phoneCategoryEn": "in a room",
    "phoneCategoryEs": "en una habitación"
  },
  {
    "id": "65",
    "description": "Interno di una cella con due finestre. Nella parete sinistra una mensola con una brocca.",
    "description_en": "The interior of a cell with two windows. On the left wall a shelf with a jug.",
    "category": "Sinister",
    "SpriteReference": "65_sprite",
    "CubemapReference": "65_HDR",
    "Narrator": "Allora, siamo in una prigione.",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "8",
    "NarratorTranslation": "We are in a prison. Here in the middle of the scene you see an object. Ok.",
    "NarratorTranslationEs": "Estamos en una prisión. Aquí, en medio de la escena, ven un objeto. Bien.",
    "phoneCategoryIt": "in una cella",
    "phoneCategoryEn": "in a cell",
    "phoneCategoryEs": "en una celda"
  },
  {
    "id": "66",
    "description": "Siamo al circo, c'é una grande faccia gioco, con occhi gialli e bocca aperta, circondata dalle fiamme.",
    "description_en": "We are at the circus, there is a large toy face with yellow eyes and an open mouth, surrounded by flames!",
    "category": "Festive",
    "SpriteReference": "66_sprite",
    "CubemapReference": "66_HDR",
    "Narrator": "Eccoci. Allora siamo di nuovo al circo, il posto perfetto per voi due.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "10.2",
    "NarratorTranslation": "Here we are. So we are back at the circus, the perfect place for you two. In the middle of the scene, an object...",
    "NarratorTranslationEs": "Aquí estamos. De vuelta en el circo, el lugar perfecto para ustedes dos. En medio de la escena, un objeto...",
    "phoneCategoryIt": "al circo",
    "phoneCategoryEn": "at the circus",
    "phoneCategoryEs": "en el circo"
  },
  {
    "id": "67",
    "description": "Ingresso di una prigione con colonne squadrate che reggono le volte.",
    "description_en": "Entrance to a prison with square columns that support the vaults. On the right, an opened door..",
    "category": "Sinister",
    "SpriteReference": "67_sprite",
    "CubemapReference": "67_HDR",
    "Narrator": "Allora, siamo in una prigione.",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "7.1",
    "NarratorTranslation": "We are in a prison. Here in the middle of the scene you see an object. Ok.",
    "NarratorTranslationEs": "Estamos en una prisión. Aquí, en medio de la escena, ven un objeto. Bien.",
    "phoneCategoryIt": "in una prigione",
    "phoneCategoryEn": "in a prison",
    "phoneCategoryEs": "en una prisión"
  },
  {
    "id": "71",
    "description": "In secondo piano si trovano alcune case vicino ad un lago montano che si intravede dietro una cortina di alberi.",
    "description_en": "A mountain scene. There is a house near a mountain lake, and a forest of green trees behind the house.",
    "category": "OutdoorNature",
    "SpriteReference": "71_sprite",
    "CubemapReference": "71_HDR",
    "Narrator": "Cominciamo. Siamo in bassa montagna. Guardate che bel paesaggio.",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "9.8",
    "NarratorTranslation": "Let's start. We are by some low mountains. Look at the beautiful landscape. In the middle of the scene, an object..",
    "NarratorTranslationEs": "Comencemos. Estamos junto a unas montañas bajas. Observen el hermoso paisaje. En medio de la escena, un objeto...",
    "phoneCategoryIt": "in montagna",
    "phoneCategoryEn": "in the mountains",
    "phoneCategoryEs": "en las montañas"
  },
  {
    "id": "72",
    "description": "Semplici tombe sono allineate ai lati del vialetto del cimitero. Nel fondo si vede il muro col cancello e alcuni cipressi.",
    "description_en": "Some simple looking graves line the sides of the cemetery driveway. In the background, a gated wall and some cypress trees.",
    "category": "Sinister",
    "SpriteReference": "72_sprite",
    "CubemapReference": "72_HDR",
    "Narrator": "Eccoci. Guardiamoci intorno - una scena piuttosto sinistra.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "7.8",
    "NarratorTranslation": "Here we are. Let's look around - a rather sinister scene. In the middle you see an object",
    "NarratorTranslationEs": "Aquí estamos. Miremos a nuestro alrededor: una escena bastante siniestra. En medio ven un objeto.",
    "phoneCategoryIt": "al cimitero",
    "phoneCategoryEn": "at the cemetery",
    "phoneCategoryEs": "en el cementerio"
  },
  {
    "id": "73",
    "description": "Vista di Piazza San Marco verso la laguna, con le colonne che reggono rispettivamente il leone di San Marco e la staua di San Giorgio e il drago. Al di là della laguna, l'isola di San Giorgio e la Giudecca.",
    "description_en": "A view of Piazza San Marco in Venice, opening towards the lagoon, with the columns supporting a lion of and a defeated dragon. Across the lagoon, the island of San Giorgio.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "73_sprite",
    "CubemapReference": "73_HDR",
    "Narrator": "Iniziamo. La scena è a Piazza San Marco, coi leoni e la laguna.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "11.8",
    "NarratorTranslation": "Let's begin. The scene is in Piazza San Marco, with the lions and the lagoon. In the middle you see an object, ok?",
    "NarratorTranslationEs": "Comencemos. La escena está en la Plaza de San Marcos, con los leones y la laguna. En medio ven un objeto, ¿de acuerdo?",
    "phoneCategoryIt": "a Venezia",
    "phoneCategoryEn": "in Venice",
    "phoneCategoryEs": "en Venecia"
  },
  {
    "id": "74",
    "description": "Una stanza arredata con una cassapanca e un panchetto, su cui si trovano una brocca e un fiasco. Ad un chiodo nella parete è appeso un indumento blu. Nella parete di fondo la finestra ha un vetro rotto e fra freschino.",
    "description_en": "A room furnished with a chest and a stool, on which are a jug and a flask. A blue garment hangs on a nail in the wall. On the back wall the window has a broken pane and is a bit chilly.",
    "category": "InteriorHumble",
    "SpriteReference": "74_sprite",
    "CubemapReference": "74_HDR",
    "Narrator": "Ok iniziamo.. Siamo in una stanza umile, un po' fredda, con una finestra rotta, una giacca blu appesa. Insomma una fetenzia.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "8.4",
    "NarratorTranslation": "Ok, we are in a humble room, a little cold, with a broken window. In the middle is an object...",
    "NarratorTranslationEs": "Bien, estamos en una habitación humilde, un poco fría, con una ventana rota. En medio hay un objeto...",
    "phoneCategoryIt": "in una stanza",
    "phoneCategoryEn": "in a room",
    "phoneCategoryEs": "en una habitación"
  },
  {
    "id": "75",
    "description": "Piazza con una chiesa, un edificio giallo a sinistra e uno azzurro a destra.",
    "description_en": "A calm square with a church, a yellowish building on the left, and a light blue one on the right.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "75_sprite",
    "CubemapReference": "75_HDR",
    "Narrator": "Eccoci, partiamo dalla scena. Siamo in piazza.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "11",
    "NarratorTranslation": "Ok, let's start from the scene, we are in a square, and in the middle of the scene you can see a prop.",
    "NarratorTranslationEs": "Bien, comencemos con la escena: estamos en una plaza, y en medio de la escena pueden ver un utensilio.",
    "phoneCategoryIt": "in piazza",
    "phoneCategoryEn": "in a square",
    "phoneCategoryEs": "en una plaza"
  },
  {
    "id": "76",
    "description": "Grotta o miniera. Nel fondo si vede un piccolo passaggio.",
    "description_en": "A mine, and at the bottom, in the back, there's a small passage.",
    "category": "Sinister",
    "SpriteReference": "76_sprite",
    "CubemapReference": "76_HDR",
    "Narrator": "Ok. Siamo in una grotta.",
    "NarratorLengthIt": "6.7",
    "NarratorLength": "6.2",
    "NarratorTranslation": "We are in a cave. At the center you see an object.",
    "NarratorTranslationEs": "Estamos en una cueva. En el centro ven un objeto.",
    "phoneCategoryIt": "in una miniera",
    "phoneCategoryEn": "in a mine",
    "phoneCategoryEs": "en una mina"
  },
  {
    "id": "77",
    "description": "Grotta con laghetto sotterraneo o forse grotta costiera in cui si insinua il mare.",
    "description_en": "A cave with an underground lake, and sharp rocks resembling teeth.",
    "category": "Sinister",
    "SpriteReference": "77_sprite",
    "CubemapReference": "77_HDR",
    "Narrator": "Bene iniziamo dalla scena, immedesimatevi. É alquanto strana. E guardate l'oggetto al centro. Ok?",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "13.8",
    "NarratorTranslation": "Well, let's start with the scene, immerse yourselves. It's quite strange. In the center of the scene, an object. Ok?",
    "NarratorTranslationEs": "Bueno, empecemos con la escena, sumérjanse. Es bastante extraña. En el centro de la escena, un objeto. ¿De acuerdo?",
    "phoneCategoryIt": "in una grotta",
    "phoneCategoryEn": "in a cave",
    "phoneCategoryEs": "en una cueva"
  },
  {
    "id": "78",
    "description": "Castello con mura merlate e torrioni.",
    "description_en": "A castle, in the desert, with cracked walls and towers.",
    "category": "OutdoorNature",
    "SpriteReference": "78_sprite",
    "CubemapReference": "78_HDR",
    "Narrator": "Bene iniziamo dalla scena. Immedesimatevi. É alquanto strana.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "13.2",
    "NarratorTranslation": "Well, let's start with the scene, immerse yourselves. It's quite strange. In the center of the scene, an object. Ok?",
    "NarratorTranslationEs": "Bueno, empecemos con la escena, sumérjanse. Es bastante extraña. En el centro de la escena, un objeto. ¿De acuerdo?",
    "phoneCategoryIt": "in un castello",
    "phoneCategoryEn": "in a castle",
    "phoneCategoryEs": "en un castillo"
  },
  {
    "id": "79",
    "description": "A sinistra è raffigurata parte di una casa. Dalla casa parte un muretto con cancello che dà accesso a una carraia. A destra, dietro il muretto un albero si protende verso il centro della scena.",
    "description_en": "An organge brick house in the countryside. From the house a low wall with a gate extens, with a small road behind and a tree on the right.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "79_sprite",
    "CubemapReference": "79_HDR",
    "Narrator": "Cominciamo. Siamo in bassa montagna. Guardate che bel paesaggio.",
    "NarratorLengthIt": "7",
    "NarratorLength": "13",
    "NarratorTranslation": "Let's start. We are by some low mountains. Look at the beautiful landscape. In the middle of the scene, an object..",
    "NarratorTranslationEs": "Empecemos. Estamos junto a unas montañas bajas. Miren el hermoso paisaje. En medio de la escena, un objeto...",
    "phoneCategoryIt": "in campagna",
    "phoneCategoryEn": "in the countryside",
    "phoneCategoryEs": "en el campo"
  },
  {
    "id": "80",
    "description": "A destra è raffigurato lo scorcio di un castello con mura merlate. Nello sfondo si vede uno specchio di mare delimitato da un promontorio in fondo al quale si erge un faro.",
    "description_en": "A sea bordered by a promontory, at the end of which stands a lighthouse. On the right, in the front, there's a glimpse of a castle with crenellated walls.",
    "category": "OutdoorNature",
    "SpriteReference": "80_sprite",
    "CubemapReference": "80_HDR",
    "Narrator": "Bene, siamo al mare, una bella scena.",
    "NarratorLengthIt": "6.2",
    "NarratorLength": "8.2",
    "NarratorTranslation": "Nice, we are at the seaside, a nice scene. Here on stage is an object...",
    "NarratorTranslationEs": "Genial, estamos a la orilla del mar, una escena bonita. Aquí en el escenario hay un objeto...",
    "phoneCategoryIt": "al mare",
    "phoneCategoryEn": "at the sea",
    "phoneCategoryEs": "en el mar"
  },
  {
    "id": "81",
    "description": "Stanza dalle pareti azzurre. Nella parete di fondo una porta con specchiature verdi. Nella stanza non ci sono mobili, alle pareti sono appesi due quadri e uno specchio.",
    "description_en": "A regal room with blue walls. On the back wall a door with green mirrors. There is no furniture in the room, two paintings and a mirror hang on the walls.",
    "category": "InteriorRegal",
    "SpriteReference": "81_sprite",
    "CubemapReference": "81_HDR",
    "Narrator": "Maschere, in questa scena siete in una bella stanza, una stanza da signori.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "11",
    "NarratorTranslation": "Ok, you are in a nice room, a gentleman's room. In the center you see an object",
    "NarratorTranslationEs": "Bueno, estamos en una hermosa habitación real. En el centro de la escena, un objeto.",
    "phoneCategoryIt": "in una villa",
    "phoneCategoryEn": "in a villa",
    "phoneCategoryEs": "en una villa"
  },
  {
    "id": "82",
    "description": "A destra si vede Palazzo Re Enzo e in fondo le due torri.",
    "description_en": "We are in Bologna. View of a square with the two towers in the background.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "82_sprite",
    "CubemapReference": "82_HDR",
    "Narrator": "Ok iniziamo... Siamo in Piazza Maggiore! a casa nostra.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "7.9",
    "NarratorTranslation": "Ok we are in.... Piazza Maggiore! Our home. In the middle of the scene, an object",
    "NarratorTranslationEs": "Bien, estamos en... ¡Piazza Maggiore! Nuestra casa. En el centro de la escena, un objeto.",
    "phoneCategoryIt": "in piazza",
    "phoneCategoryEn": "in a square",
    "phoneCategoryEs": "en una plaza"
  },
  {
    "id": "83",
    "description": "Veduta del colle della Guardia col Santuario di San Luca e di una parte del portico che da Bologna conduce al Santuario.",
    "description_en": "View of Bologna's hill where the famous Sanctuary of San Luca stands, and the portico that leads to it.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "83_sprite",
    "CubemapReference": "83_HDR",
    "Narrator": "Ahh… Siamo a San Luca!",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "6.6",
    "NarratorTranslation": "Ok, we are in San Luca, and in the middle of the scene is an object...",
    "NarratorTranslationEs": "Bien, estamos en San Luca, y en medio de la escena hay un objeto...",
    "phoneCategoryIt": "a Bologna",
    "phoneCategoryEn": "in Bologna",
    "phoneCategoryEs": "en Bolonia"
  },
  {
    "id": "86",
    "description": "Un viottolo si inoltra nella campagna passando in mezzo ad alcuni cipressi. Nello sfondo un paesaggio collinare. Il cielo ha una sfumatura rosata di alba o tramonto.",
    "description_en": "A serene view of a small path in the countryside, passing between cypress trees. In the background hillds. The sky is pink, at dusk.",
    "category": "OutdoorNature",
    "SpriteReference": "86_sprite",
    "CubemapReference": "86_HDR",
    "Narrator": "Cominciamo. Siamo in bassa montagna. Guardate che bel paesaggio.",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "12.6",
    "NarratorTranslation": "Let's start. We are by some low mountains. Look at the beautiful landscape. In the middle of the scene, an object..",
    "NarratorTranslationEs": "Comencemos. Estamos junto a unas montañas bajas. Observa el hermoso paisaje. En el centro de la escena, un objeto...",
    "phoneCategoryIt": "in campagna",
    "phoneCategoryEn": "in the countryside",
    "phoneCategoryEs": "en el campo"
  },
  {
    "id": "87",
    "description": "Veduta di piazza Maggiore con Palazzo d'Accursio con l'orologio, il Palazzo de' Notai e la scalinata di San Petronio.",
    "description_en": "Bologna, view of a Piazza Maggiore with the infamous palaces around it, and the steps of its large church",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "87_sprite",
    "CubemapReference": "87_HDR",
    "Narrator": "Ok iniziamo... Siamo in Piazza Maggiore! a casa nostra.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "12.4",
    "NarratorTranslation": "Ok we are in.... Piazza Maggiore! Our home. In the middle of the scene, an object",
    "NarratorTranslationEs": "Bien, estamos en... ¡Piazza Maggiore! Nuestra casa. En el centro de la escena, un objeto.",
    "phoneCategoryIt": "in piazza",
    "phoneCategoryEn": "in a square",
    "phoneCategoryEs": "en una plaza"
  },
  {
    "id": "91",
    "description": "Piazza su cui danno edifici dai muri rosa e ocra. Nel fondo porta di città con mura merlate e torre con orologio.",
    "description_en": "A square overlooked by buildings with pink and ochre walls. In the background, a city gate, and a clock tower.",
    "category": "Festive",
    "SpriteReference": "91_sprite",
    "CubemapReference": "91_HDR",
    "Narrator": "Bene, iniziamo. Siamo in una piazzetta, con dei bei muri rosa e una torre con l'orologio. Al centro, un oggetto.  ok?",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "12.2",
    "NarratorTranslation": "Okay, let's start. We are in a little square, with nice pink walls and a clock tower. In the center, an object.",
    "NarratorTranslationEs": "Bien, comencemos. Estamos en una pequeña plaza, con bonitas paredes rosas y una torre de reloj. En el centro, un objeto.",
    "phoneCategoryIt": "in piazza",
    "phoneCategoryEn": "in a square",
    "phoneCategoryEs": "en una plaza"
  },
  {
    "id": "96",
    "description": "Su di un'altura si vede un castello con torri e bifore.",
    "description_en": "In the mountains, on a hill is a castle with towers, windows and a tiny road leading to it.",
    "category": "OutdoorNature",
    "SpriteReference": "96_sprite",
    "CubemapReference": "96_HDR",
    "Narrator": "Cominciamo. Siamo in bassa montagna. Guardate che bel paesaggio.",
    "NarratorLengthIt": "7.3",
    "NarratorLength": "10.6",
    "NarratorTranslation": "Let's start. We are by some low mountains. Look at the beautiful landscape. In the middle of the scene, an object..",
    "NarratorTranslationEs": "Comencemos. Estamos junto a unas montañas bajas. Observa el hermoso paisaje. En el centro de la escena, un objeto...",
    "phoneCategoryIt": "in montagna",
    "phoneCategoryEn": "in a mountain",
    "phoneCategoryEs": "en una montaña"
  },
  {
    "id": "98",
    "description": "Interno di cascina con bucato steso.",
    "description_en": "Interior of a farmhouse with laundry hanging out to dry.",
    "category": "OutdoorNature",
    "SpriteReference": "98_sprite",
    "CubemapReference": "98_HDR",
    "Narrator": "Eccoci. Questa scena é in una cascina, e qualcuno ha steso il bucato.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "11",
    "NarratorTranslation": "Here we are. This scene is in a farmhouse, and someone has hung the laundry. Look in the middle, you see, there's something else...",
    "NarratorTranslationEs": "Aquí estamos. Esta escena es en una casa de campo, y alguien ha tendido la ropa. Mira en el centro, ves, hay algo más...",
    "phoneCategoryIt": "in una cascina",
    "phoneCategoryEn": "in a farmhouse",
    "phoneCategoryEs": "en una casa de campo"
  },
  {
    "id": "99",
    "description": "Nella stanza si vedono un cassettone con specchio, un camino acceso e un dipinto col volto di Cristo.",
    "description_en": "A room with a chest of drawers, a lit fireplace and a painting of the face of Jesus.",
    "category": "InteriorHumble",
    "SpriteReference": "99_sprite",
    "CubemapReference": "99_HDR",
    "Narrator": "Eccoci. Che tristezza sta stanza eh..?",
    "NarratorLengthIt": "7.1",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Here we are. How sad is this room... And in the middle of the scene is a prop.",
    "NarratorTranslationEs": "Aquí estamos. Qué triste es esta habitación... Y en el centro de la escena hay un utensilio.",
    "phoneCategoryIt": "in una sala",
    "phoneCategoryEn": "in a hall",
    "phoneCategoryEs": "en una salón"
  },
  {
    "id": "101",
    "description": "Una chiesa sulla riva di un fiume attraversato da un ponticello. Una stradina separa la chiesa da un borgo. Nello sfondo una rupe con una rocca.",
    "description_en": "A church on the bank of a mountain river, crossed by a small bridge. A small road separates the church from a mountain village. In the background a cliff with a fortress.",
    "category": "OutdoorNature",
    "SpriteReference": "101_sprite",
    "CubemapReference": "101_HDR",
    "Narrator": "Cominciamo. Siamo in bassa montagna. Guardate che bel paesaggio.",
    "NarratorLengthIt": "7.1",
    "NarratorLength": "11.8",
    "NarratorTranslation": "Let's start. We are by some low mountains. Look at the beautiful landscape. In the middle of the scene, an object..",
    "NarratorTranslationEs": "Comencemos. Estamos junto a unas montañas bajas. Observa el hermoso paisaje. En el centro de la escena, un objeto...",
    "phoneCategoryIt": "in montagna",
    "phoneCategoryEn": "in the mountains",
    "phoneCategoryEs": "en las montañas"
  },
  {
    "id": "102",
    "description": "Veduta di piazza dall'angolo di un portico. Nel lato più lontano della piazza inizia una strada in fondo alla quale si vede lo scorcio di una chiesa.",
    "description_en": "A square seen from underneath a portico. On the far side of the square begins a road, and behind it the glimpse of a church.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "102_sprite",
    "CubemapReference": "102_HDR",
    "Narrator": "Eccoci, partiamo dalla scena. Siamo in piazza.",
    "NarratorLengthIt": "9.1",
    "NarratorLength": "9.2",
    "NarratorTranslation": "Ok, let's start from the scene, we are in a square, and in the middle of the scene you can see a prop.",
    "NarratorTranslationEs": "Bien, comencemos desde la escena: estamos en una plaza, y en el centro de la escena se puede ver un utensilio.",
    "phoneCategoryIt": "in piazza",
    "phoneCategoryEn": "in a square",
    "phoneCategoryEs": "en una plaza"
  },
  {
    "id": "105",
    "description": "Un giardino chiuso con un elaborato cancello. Al centro della scena una vasca circolare con una statuetta al centro.",
    "description_en": "A villa garden, enclosed by an elaborate gate. In the center of the scene, a fancy fountain with a statuette.",
    "category": "OutdoorNature",
    "SpriteReference": "105_sprite",
    "CubemapReference": "105_HDR",
    "Narrator": "Allora, studiamo la scena. Un giardino con cancello, fontana. E qua in mezzo, un oggetto. ok?",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "7.6",
    "NarratorTranslation": "So, let's study the scene. A garden with a gate, a fountain., and in the middle, an object",
    "NarratorTranslationEs": "Estudiemos la escena. Un jardín con una puerta, una fuente y, en el centro, un objeto.",
    "phoneCategoryIt": "in giardino",
    "phoneCategoryEn": "in a garden",
    "phoneCategoryEs": "en un jardín"
  },
  {
    "id": "106",
    "description": "Veduta notturna di castello con mura merlate e torri, circondato da fossato e con ponte levatoio all'ingresso",
    "description_en": "Serene night view of a castle with walls and towers, surrounded by a small canal, and with a drawbridge at the entrance",
    "category": "Night",
    "SpriteReference": "106_sprite",
    "CubemapReference": "106_HDR",
    "Narrator": "Allora in questa scena c'é un castello circondato da un fossato. Ok? Ok.",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "11",
    "NarratorTranslation": "So in this scene there is a castle surrounded by a canal. And in the middle of the scene, there is....",
    "NarratorTranslationEs": "En esta escena hay un castillo rodeado por un canal. Y, en el centro, hay...",
    "phoneCategoryIt": "in un castello",
    "phoneCategoryEn": "in a castle",
    "phoneCategoryEs": "en un castillo"
  },
  {
    "id": "107",
    "description": "Cucina con camino e acquaio arredata con vari suppellettili e una panca.",
    "description_en": "A humble kitchen with a fireplace and sink, and a bench.",
    "category": "InteriorHumble",
    "SpriteReference": "107_sprite",
    "CubemapReference": "107_HDR",
    "Narrator": "Allora, vi trovate in una cucina, semplice ma attrezzata. E qua in mezzo, un oggetto.  ok?",
    "NarratorLengthIt": "10.7",
    "NarratorLength": "10.5",
    "NarratorTranslation": "So, you are in a kitchen, simple but equipped. And here in the middle, an object. Ok?",
    "NarratorTranslationEs": "Estás en una cocina, sencilla pero equipada. Y aquí, en el centro, un objeto. ¿De acuerdo?",
    "phoneCategoryIt": "in cucina",
    "phoneCategoryEn": "in the kitchen",
    "phoneCategoryEs": "en la cocina"
  }
]

const Backdrops = {
    getAll: function(){
        return all;
    },
    getRandom: function(){
        return all[ Math.floor(Math.random() * all.length) ];
    },
    getByID: function( id ){
      if( typeof id === 'undefined') return false;
      if( typeof id !== 'string' ){
        id = id.toString();
      }
      return all.find( ( backdrop ) => backdrop.id === id );
    }
}

export default Backdrops;