const all = [
  {
    "id": "1",
    "description": "Dall'interno della grotta si guarda verso l'uscita. L'azzurro dell'acqua si riflette sulla volta e sulle pareti dell'antro. Notte con luna.",
    "description_en": "From inside the cave you look towards the exit. The blue of the water is reflected on the vault and walls of the cave. Night with moon.",
    "category": "Night",
    "SpriteReference": "1_sprite",
    "CubemapReference": "1_HDR",
    "Narrator": "É notte, c'é la luna.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Ok so - it's night, the moon is out. At the center of the scene an object...",
    "phoneCategoryIt": "in una grotta",
    "phoneCategoryEn": ""
  },
  {
    "id": "2",
    "description": "Portico con volte a crociera e scale. Dagli occhi di portico si intravede un cortile. Notte.",
    "description_en": "Portico with cross vaults and stairs. From the eyes of the portico you can glimpse a courtyard. Night.",
    "category": "Night",
    "SpriteReference": "2_sprite",
    "CubemapReference": "2_HDR",
    "Narrator": "Ok! Si comincia. Studiamo la scena: portico, volte, cortile… e notte.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Let's begin, let's study the scene: portico, vaults, courtyard, night.. at the center of the scene an object",
    "phoneCategoryIt": "in un portico",
    "phoneCategoryEn": ""
  },
  {
    "id": "3",
    "description": "Notte, luna piena. Un vialetto di cimitero circondato da cipressi si snoda fra tombe di varie tipologie. In fondo si intravede l'uscita del cimitero.",
    "description_en": "Night, full moon. A cemetery path surrounded by cypress trees winds between tombs of various types. At the end you can glimpse the exit of the cemetery.",
    "category": "Night",
    "SpriteReference": "3_sprite",
    "CubemapReference": "3_HDR",
    "Narrator": "É notte, c'é la luna.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Ok so - it's night, the moon is out, in the middle of the scene is an object",
    "phoneCategoryIt": "al cimitero",
    "phoneCategoryEn": ""
  },
  {
    "id": "4",
    "description": "Un ampio androne con passaggi dai soffitti a volta è illuminato da una lama di luce che sembra venire dall'interno del castello. Da uno dei passaggi si vede un cortile interno. Notte.",
    "description_en": "A large entrance hall with passages with vaulted ceilings is illuminated by a blade of light that seems to come from inside the castle. From one of the passages you can see an internal courtyard. Night.",
    "category": "Night",
    "SpriteReference": "4_sprite",
    "CubemapReference": "4_HDR",
    "Narrator": "É notte, c'é la luna.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Ok so - it's night, the moon is out, in the middle of the scene is an object...",
    "phoneCategoryIt": "in un androne",
    "phoneCategoryEn": ""
  },
  {
    "id": "5",
    "description": "Veduta di piazza con chiesa e campanile nel fondo. A destra un palazzo con portico. Nella piazza sono presenti numerosi lampioni che gettano la loro lunga ombra nel chiaro di luna della notte.",
    "description_en": "View of a square with a church and bell tower in the background. On the right, a building with a portico. In the square there are numerous street lamps that cast their long shadows in the moonlight of the night.",
    "category": "Night",
    "SpriteReference": "5_sprite",
    "CubemapReference": "5_HDR",
    "Narrator": "É notte, c'é la luna.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Ok so - it's night, the moon is out, in the middle of the scene is an object...",
    "phoneCategoryIt": "in piazza",
    "phoneCategoryEn": ""
  },
  {
    "id": "6",
    "description": "Visione notturna di un tranquillo chiostro, circondato da un portico.",
    "description_en": "Night view of a quiet cloister, surrounded by a portico.",
    "category": "Night",
    "SpriteReference": "6_sprite",
    "CubemapReference": "6_HDR",
    "Narrator": "Allora, questa scena si svolge di notte. Siamo in un portico tranquillo.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "So, this scene takes place at night, we are in a quiet porch. In the middle of the scene is an object",
    "phoneCategoryIt": "in un chiostro",
    "phoneCategoryEn": ""
  },
  {
    "id": "7",
    "description": "Venezia, con l'isola di San Giorgio e la laguna illuminate dalla luna di notte.",
    "description_en": "Venice, with the island of San Giorgio and the lagoon illuminated by the moon at night.",
    "category": "Night",
    "SpriteReference": "7_sprite",
    "CubemapReference": "7_HDR",
    "Narrator": "Allora. Siamo a Venezia.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "So, we are in Venice. In the middle of the scene is an object",
    "phoneCategoryIt": "a Venezia",
    "phoneCategoryEn": ""
  },
  {
    "id": "8",
    "description": "La luna raffigurata come un volto di profilo sorge su un globo azzurro.",
    "description_en": "The moon depicted as a face in profile rises on a blue globe.",
    "category": "Night",
    "SpriteReference": "8_sprite",
    "CubemapReference": "8_HDR",
    "Narrator": "Qua dobbiamo usare l'immaginazione maschere. Improvvisiamo una scena astratta, con la luna che guarda un globo.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Here we have to use imagination masks. We see the moon looking at a globe. In the middle of the scene is an object",
    "phoneCategoryIt": "in cielo",
    "phoneCategoryEn": ""
  },
  {
    "id": "9",
    "description": "Paesaggio con mare agitato da onde spumose. Nelle parte destra lo specchio di mare è delimitato da alture. Il cielo ha qualche leggera nube.",
    "description_en": "Landscape with a sea agitated by foamy waves. On the right side the sea is bordered by hills. The sky has some light clouds.",
    "category": "OutdoorNature",
    "SpriteReference": "9_sprite",
    "CubemapReference": "9_HDR",
    "Narrator": "Bene, siamo al mare, una bella scena.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Well, we are at the seaside, a beautiful scene. Here on stage is an object...",
    "phoneCategoryIt": "al mare",
    "phoneCategoryEn": ""
  },
  {
    "id": "10",
    "description": "Alcuni alberi in un paesaggio brullo. Sulla destra si vede un muretto. Nello sfondo, in lontananza, si innalzano delle colline.",
    "description_en": "Some trees in a barren landscape. On the right you can see a low wall. In the background, in the distance, some hills rise.",
    "category": "OutdoorNature",
    "SpriteReference": "10_sprite",
    "CubemapReference": "10_HDR",
    "Narrator": "Allora questa scena la facciamo all'aria aperta. Ok!?",
    "NarratorLength": "11.3",
    "NarratorTranslation": "So, this scene is outdoors, ok? And in the middle of the scene, an object...",
    "phoneCategoryIt": "in campagna",
    "phoneCategoryEn": ""
  },
  {
    "id": "11",
    "description": "Una campagna innevata, con stradine. A destra un borgo con campanile. A sinistra una casa colonica. In lontananza si vede una chiesa sullo sfondo di monti innevati.",
    "description_en": "A snow-covered countryside, with small streets. On the right a village with a bell tower. On the left a farmhouse. In the distance you can see a church against the backdrop of snow-capped mountains.",
    "category": "OutdoorNature",
    "SpriteReference": "11_sprite",
    "CubemapReference": "11_HDR",
    "Narrator": "Attenzione maschere. Siete in campagna apera ed é nevicato.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Attention masks. You are in the open countryside and it has snowed. And here in the middle is an object...",
    "phoneCategoryIt": "in campagna",
    "phoneCategoryEn": ""
  },
  {
    "id": "12",
    "description": "Tronchi d'albero a perdita d'occhio occupano quasi tutta la scena. Nella parte alta si vede l'inizio delle chiome.",
    "description_en": "Tree trunks as far as the eye can see occupy almost the entire scene. In the upper part you can see the beginning of the foliage.",
    "category": "OutdoorNature",
    "SpriteReference": "12_sprite",
    "CubemapReference": "12_HDR",
    "Narrator": "Eccoci, in questa scena siamo in una foresta piuttosto fitta.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Here we are, in this scene we are in a rather thick forest. Look in the middle, there's an object",
    "phoneCategoryIt": "in un bosco",
    "phoneCategoryEn": ""
  },
  {
    "id": "14",
    "description": "Ai piedi di alcuni alberi, fra le rocce si vede l'ingresso di una grotta.",
    "description_en": "At the foot of some trees, among the rocks you can see the entrance to a cave.",
    "category": "OutdoorNature",
    "SpriteReference": "14_sprite",
    "CubemapReference": "14_HDR",
    "Narrator": "Maschere - occhio alla scena. Siamo all'aperto, in mezzo alla natura.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Ok let's study the scene, we are outdoors, in the middle of nature, and in the center is an object",
    "phoneCategoryIt": "in campagna",
    "phoneCategoryEn": ""
  },
  {
    "id": "15",
    "description": "Nelle parte sinistra lo specchio di mare è delimitato da alture. Il cielo è sfumato di azzurro e verde chiaro.",
    "description_en": "On the left side the sea is bordered by hills. The sky is shaded in blue and light green.",
    "category": "OutdoorNature",
    "SpriteReference": "15_sprite",
    "CubemapReference": "15_HDR",
    "Narrator": "Bene, siamo al mare, una bella scena.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Nice, we are on the seaside, a nice scene. Here on stage is an object...",
    "phoneCategoryIt": "al mare",
    "phoneCategoryEn": ""
  },
  {
    "id": "16",
    "description": "Interno di prigione con colonne a sostegno delle volte. Da una finestra entra un raggio di luce che illumina parte del muro.",
    "description_en": "Interior of a prison with columns supporting the vaults. From a window a ray of light enters and illuminates part of the wall.",
    "category": "Sinister",
    "SpriteReference": "16_sprite",
    "CubemapReference": "16_HDR",
    "Narrator": "Allora, siamo in una prigione.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "We are in a prison. Here in the middle of the scene you see an object. Ok.",
    "phoneCategoryIt": "in una prigione",
    "phoneCategoryEn": ""
  },
  {
    "id": "19",
    "description": "Una bella stanza con parete verde chiaro. Mattone con marmorizzazione. Una porta tra uno specchio rettangolare ed uno ovale.",
    "description_en": "A beautiful room with a light green wall. Brick with marbling. A door between a rectangular mirror and an oval one.",
    "category": "InteriorRegal",
    "SpriteReference": "19_sprite",
    "CubemapReference": "19_HDR",
    "Narrator": "Maschere, in questa scena siete in una bella stanza, una stanza da signori.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Ok, you are in a nice room, a gentleman's room. In the center you see an object.",
    "phoneCategoryIt": "in una camera",
    "phoneCategoryEn": ""
  },
  {
    "id": "21",
    "description": "Cornicioni in varie tonalità di verde. Soffitto blu-indaco e pareti rosse.",
    "description_en": "Cornices in various shades of green. Indigo blue ceiling and red walls.",
    "category": "InteriorRegal",
    "SpriteReference": "21_sprite",
    "CubemapReference": "21_HDR",
    "Narrator": "Eccoci. Guardate che bella scena, che colori blu e rossi.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Here we are. Look at this beautiful scene, what blue and red colors. So, in the middle of the scene is an object...",
    "phoneCategoryIt": "in un atrio",
    "phoneCategoryEn": ""
  },
  {
    "id": "22",
    "description": "Un ampio androne con soffitto a volta conduce ad un cortile e ad un altro passaggio soffuso di luce rosata.",
    "description_en": "A large hall with a vaulted ceiling leads to a courtyard and another passage suffused with pink light.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "22_sprite",
    "CubemapReference": "22_HDR",
    "Narrator": "Eccoci. Che bell'edificio. Osservatelo.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Here we are. What a beautiful building. Look at it. And look at the center is an object, ok?",
    "phoneCategoryIt": "in un androne",
    "phoneCategoryEn": ""
  },
  {
    "id": "23",
    "description": "Una grande quantità di scheletri uno sopra all'altro creano una macabra porta.",
    "description_en": "A large quantity of skeletons one above the other create a macabre door.",
    "category": "Sinister",
    "SpriteReference": "23_sprite",
    "CubemapReference": "23_HDR",
    "Narrator": "Eccoci. Guardiamoci intorno - una scena piuttosto sinistra.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Here we are. Let's look around - a rather sinister scene. In the middle you see an object",
    "phoneCategoryIt": "nelle cripte",
    "phoneCategoryEn": ""
  },
  {
    "id": "26",
    "description": "Ingresso al circo con struttura che sostiene la tabella con la scritta \"circo\". Appesi alla struttura anche uno stendardo col volto di un clown e un cartello con la scritta \"questa sera ore 21\".",
    "description_en": "Entrance to the circus with a structure that supports the sign with the word \"circus\". Also hanging from the structure is a banner with the face of a clown and a sign with the words \"this evening at 9:00 p.m.\"",
    "category": "Festive",
    "SpriteReference": "26_sprite",
    "CubemapReference": "26_HDR",
    "Narrator": "Allora, siamo al circo!",
    "NarratorLength": "7.3",
    "NarratorTranslation": "So we are at the circus, and in the middle of the scene there is an object, ok?",
    "phoneCategoryIt": "al circo",
    "phoneCategoryEn": ""
  },
  {
    "id": "29",
    "description": "Sarcofagi e croci disseminati in un prato circondato da cipressi.",
    "description_en": "Sarcophagi and crosses scattered in a meadow surrounded by cypress trees.",
    "category": "Sinister",
    "SpriteReference": "29_sprite",
    "CubemapReference": "29_HDR",
    "Narrator": "Eccoci. Guardiamoci intorno - una scena piuttosto sinistra.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Here we are. Let's look around - a rather sinister scene. In the middle you see an object",
    "phoneCategoryIt": "al cimitero",
    "phoneCategoryEn": ""
  },
  {
    "id": "30",
    "description": "Sala con fuga di archi moreschi, sostenuti da colonne a tortiglione. Pareti dipinte con motivi floreali stilizzati e geometrici.",
    "description_en": "Room with a series of Moorish arches, supported by twisted columns. Walls painted with stylized floral and geometric motifs.",
    "category": "InteriorRegal",
    "SpriteReference": "30_sprite",
    "CubemapReference": "30_HDR",
    "Narrator": "bene, la scena è ambientata in un posto molto speciale, con decorazioni orientalizzanti... insomma interpretate voi.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Well, the scene is set in a very special place, with oriental decorations... you can interpret that. In the middle, an object...",
    "phoneCategoryIt": "in un atrio",
    "phoneCategoryEn": ""
  },
  {
    "id": "34",
    "description": "Sala con tre finestroni ad arco protetti da tendaggi. Pavimento a rombi rossi e blu.",
    "description_en": "Room with three arched windows protected by curtains. Floor with red and blue diamonds.",
    "category": "InteriorRegal",
    "SpriteReference": "34_sprite",
    "CubemapReference": "34_HDR",
    "Narrator": "Maschere, in questa scena siete in una bella stanza, una stanza da signori.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Ok, you are in a nice room, a gentleman's room. In the center you see an object.",
    "phoneCategoryIt": "in una sala",
    "phoneCategoryEn": ""
  },
  {
    "id": "39",
    "description": "Nella parete di fondo della sala, dipinta in azzurro, si aprono due porte schermate da tendaggi blu. Al centro della stessa parete, gli stalli dei consiglieri sono posti su una pedana.",
    "description_en": "On the back wall of the room, painted in light blue, there are two doors shielded by blue curtains. In the center of the same wall, the councilors' stalls are placed on a platform.",
    "category": "InteriorRegal",
    "SpriteReference": "39_sprite",
    "CubemapReference": "39_HDR",
    "Narrator": "Maschere, in questa scena siete in una bella stanza, una stanza da signori.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Ok, you are in a nice room, a gentleman's room. In the center you see an object.",
    "phoneCategoryIt": "in una villa",
    "phoneCategoryEn": ""
  },
  {
    "id": "40",
    "description": "Stanza vista in prospettiva centrale. Pareti di colore rosa carico. Pavimento a scacchi. Al centro della parete di fondo campeggia un orologio a pendolo.",
    "description_en": "Room seen in central perspective. Walls of deep pink color. Checkered floor. In the center of the back wall stands a pendulum clock.",
    "category": "InteriorRegal",
    "SpriteReference": "40_sprite",
    "CubemapReference": "40_HDR",
    "Narrator": "Bene, siamo in una bellissima stanza regale.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Well, we are in a beautiful royal room. In the middle of the scene, an object",
    "phoneCategoryIt": "in una villa",
    "phoneCategoryEn": ""
  },
  {
    "id": "41",
    "description": "Interno di grotta con pertugio che guarda verso il mare aperto, dove si nota uno scoglio isolato. Il cielo è nuvoloso e il mare spumoso. All'interno della grotta si vedono riflessi di luce dorata.",
    "description_en": "Interior of a cave with a hole that looks out to sea, where an isolated rock can be seen. The sky is cloudy and the sea is foamy. Inside the cave you can see reflections of golden light.",
    "category": "Sinister",
    "SpriteReference": "41_sprite",
    "CubemapReference": "41_HDR",
    "Narrator": "Ok. Siamo in una grotta.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "We are in a cave. At the center you see an object.",
    "phoneCategoryIt": "in una grotta",
    "phoneCategoryEn": ""
  },
  {
    "id": "44",
    "description": "Ingresso al circo con varco protetto da un tendaggio rosso.",
    "description_en": "Entrance to the circus with a passage protected by a red curtain.",
    "category": "Festive",
    "SpriteReference": "44_sprite",
    "CubemapReference": "44_HDR",
    "Narrator": "Allora, siamo al circo!",
    "NarratorLength": "7.3",
    "NarratorTranslation": "So we are at the circus, and in the middle of the scene there is an object, ok?",
    "phoneCategoryIt": "al circo",
    "phoneCategoryEn": ""
  },
  {
    "id": "45",
    "description": "Ampio fossato con ponte che unisce un torrione al castello.",
    "description_en": "Wide moat with a bridge that connects a tower to the castle.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "45_sprite",
    "CubemapReference": "45_HDR",
    "Narrator": "Eccoci. Che bell'edificio. Osservatelo.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Here we are. What a beautiful building. Look at it. And look at the center is an object, ok?",
    "phoneCategoryIt": "in un castello",
    "phoneCategoryEn": ""
  },
  {
    "id": "46",
    "description": "Stanza vista in prospettiva centrale dominata da un grande camino. Nel soffitto si vedono travi grezze, sotto l'intonaco si intravedono i mattoni.",
    "description_en": "Room seen in central perspective dominated by a large fireplace. In the ceiling you can see rough beams, under the plaster you can see the bricks.",
    "category": "InteriorHumble",
    "SpriteReference": "46_sprite",
    "CubemapReference": "46_HDR",
    "Narrator": "Bene, salve maschere. La scena si svolge all'interno, in una stanza con un gran camino.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Hello masks! The scene takes place indoors, in a room with a large fireplace. In the middle, an object",
    "phoneCategoryIt": "in una stanza",
    "phoneCategoryEn": ""
  },
  {
    "id": "47",
    "description": "Un'osteria. In una sala con colonne che reggono volte a crociera, si vedono un tavolo con sedie, una botte e una credenza. Attraverso un passaggio ad arco vi è l'accesso ad una scala per il piano superiore.",
    "description_en": "An inn. In a room with columns that support cross vaults, you can see a table with chairs, a barrel and a sideboard. Through an arched passage there is access to a staircase to the upper floor.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "47_sprite",
    "CubemapReference": "47_HDR",
    "Narrator": "Bene. Siamo in osteria. Una grande osteria, viva, piena!",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Ok, we are in a tavern. Here you see an object, ok?",
    "phoneCategoryIt": "in osteria",
    "phoneCategoryEn": ""
  },
  {
    "id": "48",
    "description": "Sala dal soffitto con stucchi decorativi, colonne con specchiature verdi, pavimento a scacchi. Nel fondo si apre una porta con tendaggio. Da una finestra a sinistra la luce del sole si proietta sul pavimento.",
    "description_en": "Room with a ceiling with decorative stucco, columns with green mirrors, checkered floor. In the back there is a door with a curtain. From a window on the left the sunlight is projected onto the floor.",
    "category": "InteriorRegal",
    "SpriteReference": "48_sprite",
    "CubemapReference": "48_HDR",
    "Narrator": "Maschere, in questa scena siete in una bella stanza, una stanza da signori.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Ok, you are in a nice room, a gentleman's room. In the center you see an object.",
    "phoneCategoryIt": "in una villa",
    "phoneCategoryEn": ""
  },
  {
    "id": "50",
    "description": "Al centro della scena, al vertice di una scalinata si trova il trono. A destra e a sinistra una fitta teoria di colonne e di basamenti con animali mitologici. Scena dai colori brillanti.",
    "description_en": "At the center of the scene, at the top of a staircase is the throne. On the right and left a dense series of columns and bases with mythological animals. Scene with bright colors.",
    "category": "InteriorRegal",
    "SpriteReference": "50_sprite",
    "CubemapReference": "50_HDR",
    "Narrator": "bene, la scena è ambientata in un posto molto speciale, con decorazioni orientalizzanti... insomma interpretate voi.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Well, the scene is set in a very special place, with oriental decorations... you can interpret that. In the middle, an object...",
    "phoneCategoryIt": "in un atrio",
    "phoneCategoryEn": ""
  },
  {
    "id": "54",
    "description": "Stanza vista in prospettiva centrale, piuttosto spoglia, con camino, un tavolo e una sedia.",
    "description_en": "Room seen in central perspective, rather bare, with fireplace, a table and a chair.",
    "category": "InteriorHumble",
    "SpriteReference": "54_sprite",
    "CubemapReference": "54_HDR",
    "Narrator": "Allora, siamo in una stanza abbastanza semplice.. con un caminetto.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "So, we're in a pretty simple room, with a fireplace, and in the middle of the room is an object",
    "phoneCategoryIt": "in una stanza",
    "phoneCategoryEn": ""
  },
  {
    "id": "55",
    "description": "Veduta di prospetto di un edificio, con pronao a quattro colonne e timpano, che occupa il lato di una piazza.",
    "description_en": "View of the front of a building, with a pronaos with four columns and a tympanum, which occupies the side of a square.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "55_sprite",
    "CubemapReference": "55_HDR",
    "Narrator": "Eccoci, partiamo dalla scena. Siamo in piazza.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Ok, let's start from the scene, we are in a square, and in the middle of the scene you can see a prop.",
    "phoneCategoryIt": "in piazza",
    "phoneCategoryEn": ""
  },
  {
    "id": "57",
    "description": "Entrata delle prigioni, si nota sulla destra la discesa dal castello. Su una piccola scalinata una finestra con grata e una porta. Al centro una colonna sorregge le volte.",
    "description_en": "Entrance to the prisons, you can see on the right the descent from the castle. On a small staircase a window with a grate and a door. In the center a column supports the vaults.",
    "category": "Sinister",
    "SpriteReference": "57_sprite",
    "CubemapReference": "57_HDR",
    "Narrator": "Allora, siamo in una prigione.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "We are in a prison. Here in the middle of the scene you see an object. Ok.",
    "phoneCategoryIt": "in una prigione",
    "phoneCategoryEn": ""
  },
  {
    "id": "59",
    "description": "L'arena del circo con tre ordini di stalli per gli spettatori.",
    "description_en": "The circus arena with three tiers of stalls for spectators.",
    "category": "Festive",
    "SpriteReference": "59_sprite",
    "CubemapReference": "59_HDR",
    "Narrator": "Allora. Ci troviamo in una grande arena. Molta gente! E qua in mezzo, un oggetto.  ok?",
    "NarratorLength": "9.3",
    "NarratorTranslation": "So. We are in a big arena. Lots of people! And here in the middle, an object. OK?",
    "phoneCategoryIt": "al circo",
    "phoneCategoryEn": ""
  },
  {
    "id": "64",
    "description": "Stanza umile con scala all'ingresso, arredata solo con un tavolo e una sedia.",
    "description_en": "Humble room with a staircase at the entrance, furnished only with a table and a chair.",
    "category": "InteriorHumble",
    "SpriteReference": "64_sprite",
    "CubemapReference": "64_HDR",
    "Narrator": "Eccoci. Che tristezza sta stanza eh..?",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Here we are. How sad is this room... And in the middle of the scene is a prop.",
    "phoneCategoryIt": "in una stanza",
    "phoneCategoryEn": ""
  },
  {
    "id": "65",
    "description": "Interno di una cella con due finestre. Nella parete sinistra una mensola con una brocca.",
    "description_en": "Interior of a cell with two windows. On the left wall a shelf with a jug.",
    "category": "Sinister",
    "SpriteReference": "65_sprite",
    "CubemapReference": "65_HDR",
    "Narrator": "Allora, siamo in una prigione.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "We are in a prison. Here in the middle of the scene you see an object. Ok.",
    "phoneCategoryIt": "in una cella",
    "phoneCategoryEn": ""
  },
  {
    "id": "66",
    "description": "Siamo al circo, c'é una grande faccia gioco, con occhi gialli e bocca aperta, circondata dalle fiamme.",
    "description_en": "We are at the circus, there is a large game face, with yellow eyes and an open mouth, surrounded by flames.",
    "category": "Festive",
    "SpriteReference": "66_sprite",
    "CubemapReference": "66_HDR",
    "Narrator": "Eccoci. Allora siamo di nuovo al circo, il posto perfetto per voi due.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Here we are. So we are back at the circus, the perfect place for you two. In the middle of the scene, an object...",
    "phoneCategoryIt": "al circo",
    "phoneCategoryEn": ""
  },
  {
    "id": "67",
    "description": "Ingresso di una prigione con colonne squadrate che reggono le volte.",
    "description_en": "Entrance to a prison with square columns that support the vaults.",
    "category": "Sinister",
    "SpriteReference": "67_sprite",
    "CubemapReference": "67_HDR",
    "Narrator": "Allora, siamo in una prigione.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "We are in a prison. Here in the middle of the scene you see an object. Ok.",
    "phoneCategoryIt": "in una prigione",
    "phoneCategoryEn": ""
  },
  {
    "id": "71",
    "description": "In secondo piano si trovano alcune case vicino ad un lago montano che si intravede dietro una cortina di alberi.",
    "description_en": "In the background are some houses near a mountain lake that can be glimpsed behind a curtain of trees.",
    "category": "OutdoorNature",
    "SpriteReference": "71_sprite",
    "CubemapReference": "71_HDR",
    "Narrator": "Cominciamo. Siamo in bassa montagna. Guardate che bel paesaggio.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Let's start. We are by some low mountains. Look at the beautiful landscape. In the middle of the scene, an object..",
    "phoneCategoryIt": "in montagna",
    "phoneCategoryEn": ""
  },
  {
    "id": "72",
    "description": "Semplici tombe sono allineate ai lati del vialetto del cimitero. Nel fondo si vede il muro col cancello e alcuni cipressi.",
    "description_en": "Simple graves line the sides of the cemetery driveway. In the background you can see the wall with the gate and some cypress trees.",
    "category": "Sinister",
    "SpriteReference": "72_sprite",
    "CubemapReference": "72_HDR",
    "Narrator": "Eccoci. Guardiamoci intorno - una scena piuttosto sinistra.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Here we are. Let's look around - a rather sinister scene. In the middle you see an object",
    "phoneCategoryIt": "al cimitero",
    "phoneCategoryEn": ""
  },
  {
    "id": "73",
    "description": "Vista di Piazza San Marco verso la laguna, con le colonne che reggono rispettivamente il leone di San Marco e la staua di San Giorgio e il drago. Al di là della laguna, l'isola di San Giorgio e la Giudecca.",
    "description_en": "View of Piazza San Marco towards the lagoon, with the columns supporting the lion of San Marco and the statue of San Giorgio and the dragon. Across the lagoon, the island of San Giorgio and Giudecca.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "73_sprite",
    "CubemapReference": "73_HDR",
    "Narrator": "Iniziamo. La scena è a Piazza San Marco, coi leoni e la laguna.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Let's begin. The scene is in Piazza San Marco, with the lions and the lagoon. In the middle you see an object, ok?",
    "phoneCategoryIt": "a Venezia",
    "phoneCategoryEn": ""
  },
  {
    "id": "74",
    "description": "Una stanza arredata con una cassapanca e un panchetto, su cui si trovano una brocca e un fiasco. Ad un chiodo nella parete è appeso un indumento blu. Nella parete di fondo la finestra ha un vetro rotto e fra freschino.",
    "description_en": "A room furnished with a chest and a stool, on which are a jug and a flask. A blue garment hangs on a nail in the wall. On the back wall the window has a broken pane and is a bit chilly.",
    "category": "InteriorHumble",
    "SpriteReference": "74_sprite",
    "CubemapReference": "74_HDR",
    "Narrator": "Ok iniziamo.. Siamo in una stanza umile, un po' fredda, con una finestra rotta, una giacca blu appesa. Insomma una fetenzia.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Ok, we are in a humble room, a little cold, with a broken window. In the middle is an object...",
    "phoneCategoryIt": "in una stanza",
    "phoneCategoryEn": ""
  },
  {
    "id": "75",
    "description": "Piazza con una chiesa, un edificio giallo a sinistra e uno azzurro a destra.",
    "description_en": "Square with a church, a yellow building on the left and a blue one on the right.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "75_sprite",
    "CubemapReference": "75_HDR",
    "Narrator": "Eccoci, partiamo dalla scena. Siamo in piazza.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Ok, let's start from the scene, we are in a square, and in the middle of the scene you can see a prop.",
    "phoneCategoryIt": "in piazza",
    "phoneCategoryEn": ""
  },
  {
    "id": "76",
    "description": "Grotta o miniera. Nel fondo si vede un piccolo passaggio.",
    "description_en": "Cave or mine. At the bottom you can see a small passage.",
    "category": "Sinister",
    "SpriteReference": "76_sprite",
    "CubemapReference": "76_HDR",
    "Narrator": "Ok. Siamo in una grotta.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "We are in a cave. At the center you see an object.",
    "phoneCategoryIt": "in una miniera",
    "phoneCategoryEn": ""
  },
  {
    "id": "77",
    "description": "Grotta con laghetto sotterraneo o forse grotta costiera in cui si insinua il mare.",
    "description_en": "Cave with an underground lake or perhaps a coastal cave into which the sea intrudes.",
    "category": "Sinister",
    "SpriteReference": "77_sprite",
    "CubemapReference": "77_HDR",
    "Narrator": "Bene iniziamo dalla scena, immedesimatevi. É alquanto strana. E guardate l'oggetto al centro. Ok?",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Well, let's start with the scene, immerse yourselves. It's quite strange. In the center of the scene, an object. Ok?",
    "phoneCategoryIt": "in una grotta",
    "phoneCategoryEn": ""
  },
  {
    "id": "78",
    "description": "Castello con mura merlate e torrioni.",
    "description_en": "Castle with crenellated walls and towers.",
    "category": "Sinister",
    "SpriteReference": "78_sprite",
    "CubemapReference": "78_HDR",
    "Narrator": "Bene iniziamo dalla scena. Immedesimatevi. É alquanto strana.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Well, let's start with the scene, immerse yourselves. It's quite strange. In the center of the scene, an object. Ok?",
    "phoneCategoryIt": "in un castello",
    "phoneCategoryEn": ""
  },
  {
    "id": "79",
    "description": "A sinistra è raffigurata parte di una casa. Dalla casa parte un muretto con cancello che dà accesso a una carraia. A destra, dietro il muretto un albero si protende verso il centro della scena.",
    "description_en": "On the left is part of a house. From the house starts a low wall with a gate that gives access to a carriage road. On the right, behind the low wall, a tree reaches towards the center of the scene.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "79_sprite",
    "CubemapReference": "79_HDR",
    "Narrator": "Cominciamo. Siamo in bassa montagna. Guardate che bel paesaggio.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Let's start. We are by some low mountains. Look at the beautiful landscape. In the middle of the scene, an object..",
    "phoneCategoryIt": "in campagna",
    "phoneCategoryEn": ""
  },
  {
    "id": "80",
    "description": "A destra è raffigurato lo scorcio di un castello con mura merlate. Nello sfondo si vede uno specchio di mare delimitato da un promontorio in fondo al quale si erge un faro.",
    "description_en": "On the right is a glimpse of a castle with crenellated walls. In the background is a stretch of sea bordered by a promontory at the end of which stands a lighthouse.",
    "category": "OutdoorNature",
    "SpriteReference": "80_sprite",
    "CubemapReference": "80_HDR",
    "Narrator": "Bene, siamo al mare, una bella scena.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Nice, we are on the seaside, a nice scene. Here on stage is an object...",
    "phoneCategoryIt": "al mare",
    "phoneCategoryEn": ""
  },
  {
    "id": "81",
    "description": "Stanza dalle pareti azzurre. Nella parete di fondo una porta con specchiature verdi. Nella stanza non ci sono mobili, alle pareti sono appesi due quadri e uno specchio.",
    "description_en": "Room with blue walls. On the back wall a door with green mirrors. There is no furniture in the room, two paintings and a mirror hang on the walls.",
    "category": "InteriorRegal",
    "SpriteReference": "81_sprite",
    "CubemapReference": "81_HDR",
    "Narrator": "Maschere, in questa scena siete in una bella stanza, una stanza da signori.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Ok, you are in a nice room, a gentleman's room. In the center you see an object",
    "phoneCategoryIt": "in una villa",
    "phoneCategoryEn": ""
  },
  {
    "id": "82",
    "description": "A destra si vede Palazzo Re Enzo e in fondo le due torri.",
    "description_en": "On the right you can see Palazzo Re Enzo and the two towers in the background.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "82_sprite",
    "CubemapReference": "82_HDR",
    "Narrator": "Ok iniziamo... Siamo in Piazza Maggiore! a casa nostra.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Ok we are in.... Piazza Maggiore! Our home. In the middle of the scene, an object",
    "phoneCategoryIt": "in piazza",
    "phoneCategoryEn": ""
  },
  {
    "id": "83",
    "description": "Veduta del colle della Guardia col Santuario di San Luca e di una parte del portico che da Bologna conduce al Santuario.",
    "description_en": "View of the Guardia hill with the Sanctuary of San Luca and part of the portico that leads from Bologna to the Sanctuary.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "83_sprite",
    "CubemapReference": "83_HDR",
    "Narrator": "Ahh… Siamo a San Luca!",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Ok, we are in San Luca, and in the middle of the scene is an object...",
    "phoneCategoryIt": "a Bologna",
    "phoneCategoryEn": ""
  },
  {
    "id": "86",
    "description": "Un viottolo si inoltra nella campagna passando in mezzo ad alcuni cipressi. Nello sfondo un paesaggio collinare. Il cielo ha una sfumatura rosata di alba o tramonto.",
    "description_en": "A path winds through the countryside, passing between some cypress trees. In the background a hilly landscape. The sky has a pink hue of dawn or dusk.",
    "category": "OutdoorNature",
    "SpriteReference": "86_sprite",
    "CubemapReference": "86_HDR",
    "Narrator": "Cominciamo. Siamo in bassa montagna. Guardate che bel paesaggio.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Let's start. We are by some low mountains. Look at the beautiful landscape. In the middle of the scene, an object..",
    "phoneCategoryIt": "in campagna",
    "phoneCategoryEn": ""
  },
  {
    "id": "87",
    "description": "Veduta di piazza Maggiore con Palazzo d'Accursio con l'orologio, il Palazzo de' Notai e la scalinata di San Petronio.",
    "description_en": "View of Piazza Maggiore with Palazzo d'Accursio with the clock, the Palazzo de' Notai and the steps of San Petronio.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "87_sprite",
    "CubemapReference": "87_HDR",
    "Narrator": "Ok iniziamo... Siamo in Piazza Maggiore! a casa nostra.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Ok we are in.... Piazza Maggiore! Our home. In the middle of the scene, an object",
    "phoneCategoryIt": "in piazza",
    "phoneCategoryEn": ""
  },
  {
    "id": "91",
    "description": "Piazza su cui danno edifici dai muri rosa e ocra. Nel fondo porta di città con mura merlate e torre con orologio.",
    "description_en": "Square overlooked by buildings with pink and ochre walls. In the background, a city gate with crenellated walls and a clock tower.",
    "category": "Festive",
    "SpriteReference": "91_sprite",
    "CubemapReference": "91_HDR",
    "Narrator": "Bene, iniziamo. Siamo in una piazzetta, con dei bei muri rosa e una torre con l'orologio. Al centro, un oggetto.  ok?",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Okay, let's start. We are in a little square, with nice pink walls and a clock tower. In the center, an object.",
    "phoneCategoryIt": "in piazza",
    "phoneCategoryEn": ""
  },
  {
    "id": "96",
    "description": "Su di un'altura si vede un castello con torri e bifore.",
    "description_en": "On a hill you can see a castle with towers and mullioned windows.",
    "category": "OutdoorNature",
    "SpriteReference": "96_sprite",
    "CubemapReference": "96_HDR",
    "Narrator": "Cominciamo. Siamo in bassa montagna. Guardate che bel paesaggio.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Let's start. We are by some low mountains. Look at the beautiful landscape. In the middle of the scene, an object..",
    "phoneCategoryIt": "in montagna",
    "phoneCategoryEn": ""
  },
  {
    "id": "98",
    "description": "Interno di cascina con bucato steso.",
    "description_en": "Interior of a farmhouse with laundry hanging out to dry.",
    "category": "OutdoorNature",
    "SpriteReference": "98_sprite",
    "CubemapReference": "98_HDR",
    "Narrator": "Eccoci. Questa scena é in una cascina, e qualcuno ha steso il bucato.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "Here we are. This scene is in a farmhouse, and someone has hung the laundry. Look in the middle, you see, there's something else...",
    "phoneCategoryIt": "in una cascina",
    "phoneCategoryEn": ""
  },
  {
    "id": "99",
    "description": "Nella stanza si vedono un cassettone con specchio, un camino acceso e un dipinto col volto di Cristo.",
    "description_en": "In the room you can see a chest of drawers with a mirror, a lit fireplace and a painting of the face of Christ.",
    "category": "InteriorHumble",
    "SpriteReference": "99_sprite",
    "CubemapReference": "99_HDR",
    "Narrator": "Eccoci. Che tristezza sta stanza eh..?",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Here we are. How sad is this room... And in the middle of the scene is a prop.",
    "phoneCategoryIt": "in una sala",
    "phoneCategoryEn": ""
  },
  {
    "id": "101",
    "description": "Una chiesa sulla riva di un fiume attraversato da un ponticello. Una stradina separa la chiesa da un borgo. Nello sfondo una rupe con una rocca.",
    "description_en": "A church on the bank of a river crossed by a small bridge. A small road separates the church from a village. In the background a cliff with a fortress.",
    "category": "OutdoorNature",
    "SpriteReference": "101_sprite",
    "CubemapReference": "101_HDR",
    "Narrator": "Cominciamo. Siamo in bassa montagna. Guardate che bel paesaggio.",
    "NarratorLength": "7.3",
    "NarratorTranslation": "Let's start. We are by some low mountains. Look at the beautiful landscape. In the middle of the scene, an object..",
    "phoneCategoryIt": "in montagna",
    "phoneCategoryEn": ""
  },
  {
    "id": "102",
    "description": "Veduta di piazza dall'angolo di un portico. Nel lato più lontano della piazza inizia una strada in fondo alla quale si vede lo scorcio di una chiesa.",
    "description_en": "View of the square from the corner of a portico. On the far side of the square begins a road at the end of which you can see a glimpse of a church.",
    "category": "UrbanAndVillageScenery",
    "SpriteReference": "102_sprite",
    "CubemapReference": "102_HDR",
    "Narrator": "Eccoci, partiamo dalla scena. Siamo in piazza.",
    "NarratorLength": "9.3",
    "NarratorTranslation": "Ok, let's start from the scene, we are in a square, and in the middle of the scene you can see a prop.",
    "phoneCategoryIt": "in piazza",
    "phoneCategoryEn": ""
  },
  {
    "id": "105",
    "description": "Un giardino chiuso con un elaborato cancello. Al centro della scena una vasca circolare con una statuetta al centro.",
    "description_en": "A garden enclosed by an elaborate gate. In the center of the scene is a circular basin with a statuette in the center.",
    "category": "OutdoorNature",
    "SpriteReference": "105_sprite",
    "CubemapReference": "105_HDR",
    "Narrator": "Allora, studiamo la scena. Un giardino con cancello, fontana. E qua in mezzo, un oggetto. ok?",
    "NarratorLength": "11.3",
    "NarratorTranslation": "So, let's study the scene. A garden with a gate, a fountain., and in the middle, an object",
    "phoneCategoryIt": "in giardino",
    "phoneCategoryEn": ""
  },
  {
    "id": "106",
    "description": "Veduta notturna di castello con mura merlate e torri, circondato da fossato e con ponte levatoio all'ingresso",
    "description_en": "Night view of a castle with crenellated walls and towers, surrounded by a moat and with a drawbridge at the entrance",
    "category": "Night",
    "SpriteReference": "106_sprite",
    "CubemapReference": "106_HDR",
    "Narrator": "Allora in questa scena c'é un castello circondato da un fossato. Ok? Ok.",
    "NarratorLength": "11.3",
    "NarratorTranslation": "So in this scene there is a castle surrounded by a canal. And in the middle of the scene, there is....",
    "phoneCategoryIt": "in un castello",
    "phoneCategoryEn": ""
  },
  {
    "id": "107",
    "description": "Cucina con camino e acquaio arredata con vari suppellettili e una panca.",
    "description_en": "Kitchen with fireplace and sink furnished with various furnishings and a bench.",
    "category": "InteriorHumble",
    "SpriteReference": "107_sprite",
    "CubemapReference": "107_HDR",
    "Narrator": "Allora, vi trovate in una cucina, semplice ma attrezzata. E qua in mezzo, un oggetto.  ok?",
    "NarratorLength": "11.3",
    "NarratorTranslation": "So, you are in a kitchen, simple but equipped. And here in the middle, an object. Ok?",
    "phoneCategoryIt": "in cucina",
    "phoneCategoryEn": ""
  }
];

const Backdrops = {
    getAll: function(){
        return all;
    },
    getRandom: function(){
        return all[ Math.floor(Math.random() * all.length) ];
    },
    getByID: function( id ){
      if( typeof id === 'undefined') return false;
      if( typeof id !== 'string' ){
        id = id.toString();
      }
      return all.find( ( backdrop ) => backdrop.id === id );
    }
}

export default Backdrops;